name: "Ruby RSpec"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    # services:
    #   postgres:
    #     image: postgres:11-alpine
    #     ports:
    #       - "5432:5432"
    #     env:
    #       POSTGRES_DB: rails_test
    #       POSTGRES_USER: rails
    #       POSTGRES_PASSWORD: password
    # env:
    #   RAILS_ENV: test
    #   DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Setup Ruby
        uses: actions/checkout@v3
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
        with:
          ruby-version: 2.7.6

      - name: Install Dependencies
        run: |
          sudo apt install -yqq libpq-dev
          gem install bundler

      - name: Install Gems
        run: |
          bundle install

      - name: Prepare Database
        run: |
          bundle exec rails db:prepare

      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres@localhost:5432/test.sqlite3
        run:
          bundle exec rails test
